const Constants = require("../../../common/constants");
// PLAYER NAME
export const PLAYERNAME_MAXLENGTH = Constants.PLAYERNAME_MAXLENGTH;
export const PLAYERNAME_DEFAULT = Constants.PLAYERNAME_DEFAULT;

// ROOM CODE
export const ROOMCODE_CHARACTERS = Constants.ROOMCODE_CHARACTERS;
export const ROOMCODE_LENGTH = Constants.ROOMCODE_LENGTH;

// SPYFALL PLAYER RESTRICTIONS
export const SPYFALL_MINPLAYERS = Constants.SPYFALL_MINPLAYERS
export const SPYFALL_MAXPLAYERS = Constants.SPYFALL_MAXPLAYERS
// AVALON PLAYER RESTRICTIONS
export const AVALON_MINPLAYERS = Constants.AVALON_MINPLAYERS
export const AVALON_MAXPLAYERS = Constants.AVALON_MAXPLAYERS
// SECRET DICTATOR PLAYER RESTRICTIONS
export const DICTATOR_MINPLAYERS = Constants.DICTATOR_MINPLAYERS
export const DICTATOR_MAXPLAYERS = Constants.DICTATOR_MAXPLAYERS

// POLLING TIME
export const POLLING_TIME = Constants.POLLING_TIME;
