const Constants = {
  PLAYERNAME_MAXLENGTH: 15,
  ROOMCODE_CHARACTERS: "ABCDEFGHIJKLMNPQRSTUVWXYZ0123456789",
  ROOMCODE_LENGTH: 4,
  POLLING_TIME: 3000,
  SPYFALL_MINPLAYERS: 3,
  SPYFALL_MAXPLAYERS: 8,
  AVALON_MINPLAYERS: 5,
  AVALON_MAXPLAYERS: 10,
  DICTATOR_MINPLAYERS: 5,
  DICTATOR_MAXPLAYERS: 10
};

// PLAYER NAME
export const PLAYERNAME_MAXLENGTH = Constants.PLAYERNAME_MAXLENGTH;
export const PLAYERNAME_DEFAULT = Constants.PLAYERNAME_DEFAULT;

// ROOM CODE
export const ROOMCODE_CHARACTERS = Constants.ROOMCODE_CHARACTERS;
export const ROOMCODE_LENGTH = Constants.ROOMCODE_LENGTH;

// SPYFALL PLAYER RESTRICTIONS
export const SPYFALL_MINPLAYERS = Constants.SPYFALL_MINPLAYERS;
export const SPYFALL_MAXPLAYERS = Constants.SPYFALL_MAXPLAYERS;
// AVALON PLAYER RESTRICTIONS
export const AVALON_MINPLAYERS = Constants.AVALON_MINPLAYERS;
export const AVALON_MAXPLAYERS = Constants.AVALON_MAXPLAYERS;
// SECRET DICTATOR PLAYER RESTRICTIONS
export const DICTATOR_MINPLAYERS = Constants.DICTATOR_MINPLAYERS;
export const DICTATOR_MAXPLAYERS = Constants.DICTATOR_MAXPLAYERS;

// ETC
export const POLLING_TIME = Constants.POLLING_TIME;

// BACKEND SERVER
export const TARGET_URL =
  "http://ec2-3-16-156-190.us-east-2.compute.amazonaws.com/"; //Production server
//"http://ec2-3-17-13-100.us-east-2.compute.amazonaws.com:3000/";     //Michael server for testing
