module.exports = {
  PLAYERNAME_MAXLENGTH: 15,
  PLAYERNAME_DEFAULT: "Player",
  ROOMCODE_CHARACTERS: "ABCDEFGHIJKLMNPQRSTUVWXYZ0123456789",
  ROOMCODE_LENGTH: 4,
  SPYFALL_MINPLAYERS: 3,
  SPYFALL_MAXPLAYERS: 8,
  AVALON_MINPLAYERS: 5,
  AVALON_MAXPLAYERS: 10,
  DICTATOR_MINPLAYERS: 5,
  DICTATOR_MAXPLAYERS: 10,
  POLLING_TIME: 3000
};
